'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class confirm

	'''<summary>
	'''lblSubHeading control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSubHeading As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''pnlReg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlReg As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''pnlDomainInvalid control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlDomainInvalid As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''dsDomains control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dsDomains As Global.System.Web.UI.WebControls.ObjectDataSource

	'''<summary>
	'''rptDomains control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rptDomains As Global.System.Web.UI.WebControls.Repeater
End Class
