<?xml version="1.0" encoding="utf-8"?><Database Name="dpiasandpit" Class="DPIAProjectsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-E8GS2LD;Initial Catalog=dpiatool;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dpiasandpitConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.Project_GetByID" Method="Project_GetByID">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_GetByIDResult">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Status Date]" Member="Status_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Organisation ID]" Member="Organisation_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Assigned To ID]" Member="Assigned_To_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Assigned Name]" Member="Assigned_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Assigned Email]" Member="Assigned_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Assigned Date]" Member="Assigned_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[IG Lead ID]" Member="IG_Lead_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[IG Lead Name]" Member="IG_Lead_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[IG Lead Email]" Member="IG_Lead_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[IG Lead Date]" Member="IG_Lead_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[IG Lead Sign Off Date]" Member="IG_Lead_Sign_Off_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Asset Owner ID]" Member="Asset_Owner_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Asset Owner Name]" Member="Asset_Owner_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Asset Owner Email]" Member="Asset_Owner_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Asset Owner Date]" Member="Asset_Owner_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Asset Owner Sign Off Date]" Member="Asset_Owner_Sign_Off_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[DPO ID]" Member="DPO_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[DPO Name]" Member="DPO_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[DPO Email]" Member="DPO_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[DPO Date]" Member="DPO_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[DPO Sign Off Date]" Member="DPO_Sign_Off_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[ICO ID]" Member="ICO_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[ICO Name]" Member="ICO_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[ICO Email]" Member="ICO_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[ICO Date]" Member="ICO_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[ICO Sign Off Date]" Member="ICO_Sign_Off_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Created ID]" Member="Created_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="[Created Name]" Member="Created_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Created Email]" Member="Created_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Created Date]" Member="Created_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Modified ID]" Member="Modified_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Modified Name]" Member="Modified_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Modified Email]" Member="Modified_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Modified Date]" Member="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Archived ID]" Member="Archived_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Archived Name]" Member="Archived_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Archived Email]" Member="Archived_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Archived Date]" Member="Archived_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_GetDPIAByID" Method="Project_GetDPIAByID">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_GetDPIAByIDResult">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ01" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DPIALegalQ01a" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DPIALegalQ01aa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ01ab" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ01ac" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ01ad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ01ae" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ01af" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ01acleg" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DPIALegalQ01aeleg" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DPIALegalQ01aa2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DPIALegalQ01aa3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DPIALegalQ02" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DPIALegalQ02aa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02ab" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02ac" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02ad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02ae" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02af" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02ag" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02ah" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02ai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02aga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agb" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agj" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agl" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agm" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agn" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02ago" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02ags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agv" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ02agw" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DPIALegalQ03" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DPIALegalQ04" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DPIALegalQ04b" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_GetDPIADCDPResposibilityByID" Method="Project_GetDPIADCDPResposibilityByID">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_GetDPIADCDPResposibilityByIDResult">
      <Column Name="DPIADCDPResposibilityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InformationSharedID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_GetDPIAHealthConfRespByID" Method="Project_GetDPIAHealthConfRespByID">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_GetDPIAHealthConfRespByIDResult">
      <Column Name="DPIAHealthConfRespID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InformationSharedID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_GetDPIAHealthPurposeByID" Method="Project_GetDPIAHealthPurposeByID">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_GetDPIAHealthPurposeByIDResult">
      <Column Name="DPIAHealthPurposeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InformationSharedID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_GetDPIAInformedConsentByID" Method="Project_GetDPIAInformedConsentByID">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_GetDPIAInformedConsentByIDResult">
      <Column Name="DPIAInformedConsentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InformationSharedID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_GetScreeningByID" Method="Project_GetScreeningByID">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_GetScreeningByIDResult">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="[IG Lead ID]" Member="IG_Lead_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[IG Lead Name]" Member="IG_Lead_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[IG Lead Email]" Member="IG_Lead_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[IG Lead Date]" Member="IG_Lead_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PSQ01" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ02" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ03" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ04" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ05" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ06" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ07" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ08" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ09" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ10" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ13" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ14" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ15" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ16" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ17" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQ18" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_GetScreeningV2ByID" Method="Project_GetScreeningV2ByID">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_GetScreeningV2ByIDResult">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="[IG Lead ID]" Member="IG_Lead_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[IG Lead Name]" Member="IG_Lead_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[IG Lead Email]" Member="IG_Lead_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[IG Lead Date]" Member="IG_Lead_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PSQV201a" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV201b" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV201c" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV201d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV201e" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV201f" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV201g" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV202a" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV202b" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV202c" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV202d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV202e" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV202f" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV203a" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV203b" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV203c" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV203d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV203e" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV203f" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV203g" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV203h" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV204a" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV204b" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV204c" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV204d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV204e" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV204f" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV204g" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSQV204h" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_Insert" Method="Project_Insert">
    <Parameter Name="PName" Parameter="pName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="PDescription" Parameter="pDescription" Type="System.String" DbType="NVarChar(2500)" />
    <Parameter Name="PStatusID" Parameter="pStatusID" Type="System.Decimal" DbType="Decimal(19,0)" />
    <Parameter Name="POrganisationID" Parameter="pOrganisationID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PAssignedIGLeadID" Parameter="pAssignedIGLeadID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="PAssignedIGLeadDate" Parameter="pAssignedIGLeadDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PAssignedInfAssetOwnerID" Parameter="pAssignedInfAssetOwnerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="PAssignedInfAssetOwnerDate" Parameter="pAssignedInfAssetOwnerDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PAssignedDPOID" Parameter="pAssignedDPOID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="PAssignedDPODate" Parameter="pAssignedDPODate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PAssignedICOID" Parameter="pAssignedICOID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="PAssignedICODate" Parameter="pAssignedICODate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PCreatedByID" Parameter="pCreatedByID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="Project_InsertResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_SetArchive" Method="Project_SetArchive">
    <Parameter Name="SummaryID" Parameter="summaryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ArchivedByID" Parameter="archivedByID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="Project_SetArchiveResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_Update" Method="Project_Update">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PName" Parameter="pName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="PDescription" Parameter="pDescription" Type="System.String" DbType="NVarChar(2500)" />
    <Parameter Name="PAssignedIGLeadID" Parameter="pAssignedIGLeadID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="PAssignedIGLeadDate" Parameter="pAssignedIGLeadDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PAssignedInfAssetOwnerID" Parameter="pAssignedInfAssetOwnerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="PAssignedInfAssetOwnerDate" Parameter="pAssignedInfAssetOwnerDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PAssignedDPOID" Parameter="pAssignedDPOID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="PAssignedDPODate" Parameter="pAssignedDPODate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PAssignedICOID" Parameter="pAssignedICOID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="PAssignedICODate" Parameter="pAssignedICODate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PLastModifiedID" Parameter="pLastModifiedID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="Project_UpdateResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_UpdateDPIA" Method="Project_UpdateDPIA">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PStatusID" Parameter="pStatusID" Type="System.Decimal" DbType="Decimal(19,0)" />
    <Parameter Name="DPIALegalQ01" Parameter="dPIALegalQ01" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ01a" Parameter="dPIALegalQ01a" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ01aa" Parameter="dPIALegalQ01aa" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ01ab" Parameter="dPIALegalQ01ab" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ01ac" Parameter="dPIALegalQ01ac" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ01ad" Parameter="dPIALegalQ01ad" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ01ae" Parameter="dPIALegalQ01ae" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ01af" Parameter="dPIALegalQ01af" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ01acleg" Parameter="dPIALegalQ01acleg" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="DPIALegalQ01aeleg" Parameter="dPIALegalQ01aeleg" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="DPIALegalQ01aa2" Parameter="dPIALegalQ01aa2" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ01aa3" Parameter="dPIALegalQ01aa3" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02" Parameter="dPIALegalQ02" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02aa" Parameter="dPIALegalQ02aa" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02ab" Parameter="dPIALegalQ02ab" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02ac" Parameter="dPIALegalQ02ac" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02ad" Parameter="dPIALegalQ02ad" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02ae" Parameter="dPIALegalQ02ae" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02af" Parameter="dPIALegalQ02af" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02ag" Parameter="dPIALegalQ02ag" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02ah" Parameter="dPIALegalQ02ah" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02ai" Parameter="dPIALegalQ02ai" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02aga" Parameter="dPIALegalQ02aga" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agb" Parameter="dPIALegalQ02agb" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agc" Parameter="dPIALegalQ02agc" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agd" Parameter="dPIALegalQ02agd" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02age" Parameter="dPIALegalQ02age" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agf" Parameter="dPIALegalQ02agf" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agg" Parameter="dPIALegalQ02agg" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agh" Parameter="dPIALegalQ02agh" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agi" Parameter="dPIALegalQ02agi" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agj" Parameter="dPIALegalQ02agj" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agk" Parameter="dPIALegalQ02agk" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agl" Parameter="dPIALegalQ02agl" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agm" Parameter="dPIALegalQ02agm" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agn" Parameter="dPIALegalQ02agn" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02ago" Parameter="dPIALegalQ02ago" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agp" Parameter="dPIALegalQ02agp" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agq" Parameter="dPIALegalQ02agq" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agr" Parameter="dPIALegalQ02agr" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02ags" Parameter="dPIALegalQ02ags" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agt" Parameter="dPIALegalQ02agt" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agu" Parameter="dPIALegalQ02agu" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agv" Parameter="dPIALegalQ02agv" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ02agw" Parameter="dPIALegalQ02agw" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ03" Parameter="dPIALegalQ03" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ04" Parameter="dPIALegalQ04" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ04b" Parameter="dPIALegalQ04b" Type="System.Int32" DbType="Int" />
    <Parameter Name="DPIALegalQ01aa1CSV" Parameter="dPIALegalQ01aa1CSV" Type="System.String" DbType="VarChar(400)" />
    <Parameter Name="DPIALegalQ03aCSV" Parameter="dPIALegalQ03aCSV" Type="System.String" DbType="VarChar(400)" />
    <Parameter Name="DPIALegalQ03bCSV" Parameter="dPIALegalQ03bCSV" Type="System.String" DbType="VarChar(400)" />
    <Parameter Name="DPIALegalQ04aCSV" Parameter="dPIALegalQ04aCSV" Type="System.String" DbType="VarChar(400)" />
    <Parameter Name="PLastModifiedID" Parameter="pLastModifiedID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="Project_UpdateDPIAResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_UpdateScreening" Method="Project_UpdateScreening">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PStatusID" Parameter="pStatusID" Type="System.Decimal" DbType="Decimal(19,0)" />
    <Parameter Name="PAssignedIGLeadID" Parameter="pAssignedIGLeadID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="PAssignedIGLeadDate" Parameter="pAssignedIGLeadDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PSQ01" Parameter="pSQ01" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ02" Parameter="pSQ02" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ03" Parameter="pSQ03" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ04" Parameter="pSQ04" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ05" Parameter="pSQ05" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ06" Parameter="pSQ06" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ07" Parameter="pSQ07" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ08" Parameter="pSQ08" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ09" Parameter="pSQ09" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ10" Parameter="pSQ10" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ11" Parameter="pSQ11" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ12" Parameter="pSQ12" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ13" Parameter="pSQ13" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ14" Parameter="pSQ14" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ15" Parameter="pSQ15" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ16" Parameter="pSQ16" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ17" Parameter="pSQ17" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQ18" Parameter="pSQ18" Type="System.Int32" DbType="Int" />
    <Parameter Name="PLastModifiedID" Parameter="pLastModifiedID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="Project_UpdateScreeningResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_UpdateScreeningV2" Method="Project_UpdateScreeningV2">
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PStatusID" Parameter="pStatusID" Type="System.Decimal" DbType="Decimal(19,0)" />
    <Parameter Name="PAssignedIGLeadID" Parameter="pAssignedIGLeadID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="PAssignedIGLeadDate" Parameter="pAssignedIGLeadDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PSQV201a" Parameter="pSQV201a" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV201b" Parameter="pSQV201b" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV201c" Parameter="pSQV201c" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV201d" Parameter="pSQV201d" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV201e" Parameter="pSQV201e" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV201f" Parameter="pSQV201f" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV201g" Parameter="pSQV201g" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV202a" Parameter="pSQV202a" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV202b" Parameter="pSQV202b" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV202c" Parameter="pSQV202c" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV202d" Parameter="pSQV202d" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV202e" Parameter="pSQV202e" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV202f" Parameter="pSQV202f" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV203a" Parameter="pSQV203a" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV203b" Parameter="pSQV203b" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV203c" Parameter="pSQV203c" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV203d" Parameter="pSQV203d" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV203e" Parameter="pSQV203e" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV203f" Parameter="pSQV203f" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV203g" Parameter="pSQV203g" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV203h" Parameter="pSQV203h" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV204a" Parameter="pSQV204a" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV204b" Parameter="pSQV204b" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV204c" Parameter="pSQV204c" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV204d" Parameter="pSQV204d" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV204e" Parameter="pSQV204e" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV204f" Parameter="pSQV204f" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV204g" Parameter="pSQV204g" Type="System.Int32" DbType="Int" />
    <Parameter Name="PSQV204h" Parameter="pSQV204h" Type="System.Int32" DbType="Int" />
    <Parameter Name="PLastModifiedID" Parameter="pLastModifiedID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="Project_UpdateScreeningV2Result">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Projects_GetFiltered" Method="Projects_GetFiltered">
    <Parameter Name="OrganisationID" Parameter="organisationID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="IncludeArchived" Parameter="includeArchived" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="Projects_GetFilteredResult">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Status Date]" Member="Status_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Organisation ID]" Member="Organisation_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Assigned To ID]" Member="Assigned_To_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Assigned Name]" Member="Assigned_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Assigned Email]" Member="Assigned_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Assigned Date]" Member="Assigned_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[IG Lead ID]" Member="IG_Lead_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[IG Lead Name]" Member="IG_Lead_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[IG Lead Email]" Member="IG_Lead_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[IG Lead Date]" Member="IG_Lead_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[IG Lead Sign Off Date]" Member="IG_Lead_Sign_Off_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Asset Owner ID]" Member="Asset_Owner_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Asset Owner Name]" Member="Asset_Owner_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Asset Owner Email]" Member="Asset_Owner_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Asset Owner Date]" Member="Asset_Owner_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Asset Owner Sign Off Date]" Member="Asset_Owner_Sign_Off_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[DPO ID]" Member="DPO_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[DPO Name]" Member="DPO_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[DPO Email]" Member="DPO_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[DPO Date]" Member="DPO_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[DPO Sign Off Date]" Member="DPO_Sign_Off_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[ICO ID]" Member="ICO_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[ICO Name]" Member="ICO_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[ICO Email]" Member="ICO_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[ICO Date]" Member="ICO_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[ICO Sign Off Date]" Member="ICO_Sign_Off_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Created ID]" Member="Created_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="[Created Name]" Member="Created_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Created Email]" Member="Created_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Created Date]" Member="Created_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Modified ID]" Member="Modified_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Modified Name]" Member="Modified_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Modified Email]" Member="Modified_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Modified Date]" Member="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Archived ID]" Member="Archived_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Archived Name]" Member="Archived_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Archived Email]" Member="Archived_Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Archived Date]" Member="Archived_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Users_GetOrgDPORoles" Method="Users_GetOrgDPORoles">
    <Parameter Name="OrganisationID" Parameter="organisationID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Users_GetOrgDPORolesResult">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OrganisationUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Users_GetOrgIARoles" Method="Users_GetOrgIARoles">
    <Parameter Name="OrganisationID" Parameter="organisationID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Users_GetOrgIARolesResult">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OrganisationUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Users_GetOrgIGRoles" Method="Users_GetOrgIGRoles">
    <Parameter Name="OrganisationID" Parameter="organisationID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Users_GetOrgIGRolesResult">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OrganisationUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_File_Delete" Method="Project_File_Delete">
    <Parameter Name="FileID" Parameter="fileID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Project_FileGroup_Insert" Method="Project_FileGroup_Insert">
    <Parameter Name="GroupType" Parameter="groupType" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_FileGroup_InsertResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_FileGroupFile_Insert" Method="Project_FileGroupFile_Insert">
    <Parameter Name="FileGroupID" Parameter="fileGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FileID" Parameter="fileID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_FileGroupFile_InsertResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_FileGroups_UpdateID" Method="Project_FileGroups_UpdateID">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="FileGroupID" Parameter="fileGroupID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_FileGroups_UpdateIDResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_GetFileGroupByID" Method="Project_GetFileGroupByID">
    <Parameter Name="GroupType" Parameter="groupType" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="Project_GetFileGroupByIDResult">
      <Column Name="FileGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Project_InsertFile" Method="Project_InsertFile">
    <Parameter Name="FileName" Parameter="fileName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FileType" Parameter="fileType" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FileSize" Parameter="fileSize" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FileData" Parameter="fileData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Parameter Name="OrganisationID" Parameter="organisationID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserEmail" Parameter="userEmail" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="Project_InsertFileResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Projects_GetFilesByGroup" Method="Projects_GetFilesByGroup">
    <Parameter Name="FileGroupId" Parameter="fileGroupId" Type="System.Int32" DbType="Int" />
    <ElementType Name="Projects_GetFilesByGroupResult">
      <Column Name="FileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FileSize" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FileData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="OrganisationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserEmail" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Projects_GetFilesByGroupTypeAndID" Method="Projects_GetFilesByGroupTypeAndID">
    <Parameter Name="GroupType" Parameter="groupType" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="Projects_GetFilesByGroupTypeAndIDResult">
      <Column Name="Type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FileData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FileSize" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserEmail" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="OrganisationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>