'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GridviewControlPanel
    
    '''<summary>
    '''hlPopupGVCustomise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlPopupGVCustomise As Global.DevExpress.Web.ASPxHyperLink
    
    '''<summary>
    '''bsPopupGVCustomise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsPopupGVCustomise As Global.DevExpress.Web.Bootstrap.BootstrapPopupControl
End Class
