'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin_lists
    
    '''<summary>
    '''tabSuperAdmins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabSuperAdmins As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtSuperAdmins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSuperAdmins As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tabDomains control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabDomains As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtDomains control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDomains As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''dsRegions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsRegions As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsDomains control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDomains As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsSuperAdmins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsSuperAdmins As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsAdminGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAdminGroups As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsAdminGroupsFull control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAdminGroupsFull As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsAPIKeys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAPIKeys As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsDFDTransferSystemPlatform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDTransferSystemPlatform As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsTransferPlatforms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTransferPlatforms As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''mvManageLists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvManageLists As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''vDomains control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vDomains As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''gvDomains control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDomains As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblDomainAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDomainAdd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbDomainAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDomainAdd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvDomainAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDomainAdd As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cbShowInListAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShowInListAdd As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbtAddDomain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddDomain As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''vSuperAdmins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vSuperAdmins As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''gvSuperAdmins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSuperAdmins As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lbtAddNewSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddNewSA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''vAdminGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAdminGroups As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''gvAdminGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAdminGroups As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblGroupNameAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroupNameAdd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbGroupNameAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbGroupNameAdd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblGroupContactAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroupContactAdd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbGroupContactAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbGroupContactAdd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblContractEndDateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContractEndDateAdd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbContractEndDateAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbContractEndDateAdd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEmailAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmailAdd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbEmailAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEmailAdd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblAddressAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddressAdd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbAddressAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAddressAdd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTelephoneAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTelephoneAdd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbTelephoneAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTelephoneAdd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblOrganisationLicences control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrganisationLicences As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbOrganisationLicences control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbOrganisationLicences As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRegionAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegionAdd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddRegionAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddRegionAdd As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbtAddAdminGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddAdminGroup As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''vNotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vNotifications As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''bscbIncludeOld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bscbIncludeOld As Global.DevExpress.Web.Bootstrap.BootstrapCheckBox
    
    '''<summary>
    '''dsSANotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsSANotifications As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvSANotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvSANotifications As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''vAPIKeys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAPIKeys As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''bsGVTransferPlatforms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsGVTransferPlatforms As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''bsgvAPIKeys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvAPIKeys As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''vPickLists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vPickLists As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''dsSubjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsSubjects As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvDataSubjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvDataSubjects As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsFormats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFormats As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvDataFormats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvDataFormats As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTypes As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvDataTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvDataTypes As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsAccessors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAccessors As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvAccessors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvAccessors As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsScheduleTwos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsScheduleTwos As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvScheduleTwos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvScheduleTwos As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsScheduleThrees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsScheduleThrees As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvScheduleThrees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvScheduleThrees As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDDirectionOfFlow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDDirectionOfFlow As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvDirectionOfFlow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvDirectionOfFlow As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDFrequencyOfTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDFrequencyOfTransfer As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvFrequencyOfTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvFrequencyOfTransfer As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDNumberOfRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDNumberOfRecords As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvNumberOfRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvNumberOfRecords As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDElectronicAccessedOnSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDElectronicAccessedOnSite As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvElectronicAccessedOnSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvElectronicAccessedOnSite As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDElectronicByAutomated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDElectronicByAutomated As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvElectronicByAutomated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvElectronicByAutomated As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDElectronicByEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDElectronicByEmail As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvElectronicByEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvElectronicByEmail As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDElectronicByManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDElectronicByManual As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsElectronicByManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsElectronicByManual As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDElectronicViaText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDElectronicViaText As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvElectronicViaText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvElectronicViaText As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDPaperByCourier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDPaperByCourier As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvPaperByCourier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvPaperByCourier As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDPaperByDataSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDPaperByDataSubject As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvPaperByDataSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvPaperByDataSubject As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDPaperByFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDPaperByFax As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvPaperByFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvPaperByFax As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDPaperByStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDPaperByStaff As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvPaperByStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvPaperByStaff As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDPaperByStandardPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDPaperByStandardPost As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvPaperByPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvPaperByPost As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDRemovableByCourier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDRemovableByCourier As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvRemovableByCourier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvRemovableByCourier As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDRemovableByStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDRemovableByStaff As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvRemovableByStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvRemovableByStaff As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDRemovableByStandardPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDRemovableByStandardPost As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvRemovableByStandardPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvRemovableByStandardPost As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDStorageAfterTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDStorageAfterTransfer As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvStorageAfterTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvStorageAfterTransfer As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDSecuredAfterTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDSecuredAfterTransfer As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvSecuredAfterTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvSecuredAfterTransfer As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDAccessedAfterTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDAccessedAfterTransfer As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvAccessedAfterTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvAccessedAfterTransfer As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDPrivacyChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDPrivacyChanges As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvPrivacyChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvPrivacyChanges As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDConsentModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDConsentModel As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvConsentModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvConsentModel As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDUptodateAccurateComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDUptodateAccurateComplete As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvUptodateAccurateComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvUptodateAccurateComplete As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDRetentionDisposal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDRetentionDisposal As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvRetentionDisposal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvRetentionDisposal As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDSubjectAccessRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDSubjectAccessRequests As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvSubjectAccessRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvSubjectAccessRequests As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDPoliciesProcessesSOPs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDPoliciesProcessesSOPs As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvPoliciesProcessesSOPs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvPoliciesProcessesSOPs As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDIncidentManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDIncidentManagement As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvIncidentManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvIncidentManagement As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDTrainingSystemData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDTrainingSystemData As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvTrainingSystemData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvTrainingSystemData As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDBusinessContinuity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDBusinessContinuity As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvBusinessContinuity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvBusinessContinuity As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDDisasterRecovery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDDisasterRecovery As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvDisasterRecovery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvDisasterRecovery As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDNonEEAExemptionsDerogations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDNonEEAExemptionsDerogations As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvNonEEAExemptionsDerogations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvNonEEAExemptionsDerogations As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''dsDFDSecuredReceivingOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDFDSecuredReceivingOrg As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''bsgvSecuredReceivingOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvSecuredReceivingOrg As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''lblModalHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblModalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ModalOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalOK As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblManageSATitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblManageSATitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hfSuperAdminID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSuperAdminID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbSuperAdminEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSuperAdminEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSAAdminGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSAAdminGroup As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''listAdminGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listAdminGroups As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbContentManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbContentManager As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Label11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbCentralSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCentralSA As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbtAddSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddSA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtUpdateSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtUpdateSA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblManageDomainTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblManageDomainTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hfDomainID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDomainID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''Label17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label17 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbDomain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDomain As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''Label18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label18 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbActive As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Label19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label19 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbShowInList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShowInList As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbtAddDom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddDom As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtUpdateDomain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtUpdateDomain As Global.System.Web.UI.WebControls.LinkButton
End Class
