'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin_faqs
    
    '''<summary>
    '''dsFAQs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFAQs As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsAdminGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAdminGroups As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''mvFAQs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvFAQs As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''vFAQList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vFAQList As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''gvFAQs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFAQs As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lbtAddNewFAQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddNewFAQ As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''vAddEditFAQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAddEditFAQ As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''fvFAQs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvFAQs As Global.System.Web.UI.WebControls.FormView
End Class
