'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class dpia
    
    '''<summary>
    '''lblFormTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hfProjectFileGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfProjectFileGroup As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfSPIFileGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSPIFileGroup As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfProjectID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfProjectID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfReadOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfReadOnly As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfScreeningValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfScreeningValidation As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfPFrozen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPFrozen As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''liDPIALegal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDPIALegal As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtDPIALegal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDPIALegal As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''liDPIAProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDPIAProcess As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtDPIAProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDPIAProcess As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''liDPIARights control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDPIARights As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtDPIARights control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDPIARights As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''liDPIASecurity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDPIASecurity As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtDPIASecurity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDPIASecurity As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''liDPIARisks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDPIARisks As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtDPIARisks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDPIARisks As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''liDPIADocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDPIADocuments As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtDPIADocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDPIADocuments As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''liDPIAFinalise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDPIAFinalise As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtDPIAFinalise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDPIAFinalise As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mvDPIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvDPIA As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''vLegal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vLegal As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''pnlLegal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegal As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDPIALegalQ01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblDPIALegalQ01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDPIALegalQ01 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxDPIALegalQ01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxDPIALegalQ01 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlLegalQ01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ01 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDPIALegalQ01a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01a As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblDPIALegalQ01a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDPIALegalQ01a As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxDPIALegalQ01a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxDPIALegalQ01a As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlLegalQ01a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ01a As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cbDPIALegalQ01aa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ01aa As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ01aa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01aa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ01aa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ01aa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlLegalQ01aa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ01aa As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDPIALegalQ01aa1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01aa1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cblDPIALegalQ01aa1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblDPIALegalQ01aa1 As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''lblDPIALegalQ01aa2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01aa2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblDPIALegalQ01aa2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDPIALegalQ01aa2 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxDPIALegalQ01aa2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxDPIALegalQ01aa2 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblDPIALegalQ01aa3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01aa3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblDPIALegalQ01aa3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDPIALegalQ01aa3 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxDPIALegalQ01aa3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxDPIALegalQ01aa3 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cbDPIALegalQ01ab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ01ab As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ01ab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01ab As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ01ab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ01ab As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ01ac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ01ac As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ01ac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01ac As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ01ac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ01ac As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlLegalQ01ac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ01ac As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDPIALegalQ01acleg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01acleg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbDPIALegalQ01acleg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDPIALegalQ01acleg As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rxvDPIALegalQ01acleg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rxvDPIALegalQ01acleg As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''cbDPIALegalQ01ad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ01ad As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ01ad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01ad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ01ad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ01ad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ01ae control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ01ae As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ01ae control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01ae As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ01ae control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ01ae As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlLegalQ01ae control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ01ae As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDPIALegalQ01aeleg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01aeleg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbDPIALegalQ01aeleg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDPIALegalQ01aeleg As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rxvDPIALegalQ01aeleg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rxvDPIALegalQ01aeleg As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''cbDPIALegalQ01af control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ01af As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ01af control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ01af As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ01af control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ01af As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlLegalQ01af control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ01af As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''divEvidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEvidence As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lds_SummaryFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lds_SummaryFiles As Global.System.Web.UI.WebControls.LinqDataSource
    
    '''<summary>
    '''rptFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptFiles As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFileUpload As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''filEvidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filEvidence As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbtUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtUpload As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblDPIALegalQ02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblDPIALegalQ02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDPIALegalQ02 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxDPIALegalQ02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxDPIALegalQ02 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlLegalQ02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ02 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDPIALegalQ02a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02a As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02aa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02aa As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02aa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02aa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ02aa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ02aa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02ab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02ab As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02ab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02ab As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ02ab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ02ab As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02ac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02ac As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02ac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02ac As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ02ac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ02ac As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02ad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02ad As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02ad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02ad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ02ad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ02ad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02ae control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02ae As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02ae control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02ae As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ02ae control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ02ae As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02af control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02af As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02af control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02af As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ02af control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ02af As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02ag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02ag As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02ag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02ag As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ02ag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ02ag As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlLegalQ02ag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ02ag As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cbDPIALegalQ02aga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02aga As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02aga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02aga As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agb As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agc As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agd As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02age As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02age As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agf As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agf As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agg As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agh As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agh As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agi As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agi As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agj As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agj As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agk As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agk As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agl As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agm As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agm As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agn As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agn As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02ago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02ago As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02ago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02ago As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agp As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agq As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agq As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agr As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02ags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02ags As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02ags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02ags As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agt As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agu As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agu As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agv As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02agw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02agw As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02agw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02agw As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlLegalQ02agfiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ02agfiles As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lds_SPISummaryFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lds_SPISummaryFiles As Global.System.Web.UI.WebControls.LinqDataSource
    
    '''<summary>
    '''rptSPIFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSPIFiles As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlSPIFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSPIFileUpload As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''filSPIEvidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filSPIEvidence As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbtSPIUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSPIUpload As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''cbDPIALegalQ02ah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02ah As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02ah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02ah As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ02ah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ02ah As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDPIALegalQ02ai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPIALegalQ02ai As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDPIALegalQ02ai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ02ai As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl2DPIALegalQ02ai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2DPIALegalQ02ai As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDPIALegalQ03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ03 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblDPIALegalQ03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDPIALegalQ03 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxDPIALegalQ03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxDPIALegalQ03 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlLegalQ03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ03 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDPIALegalQ03a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ03a As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cblDPIALegalQ03a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblDPIALegalQ03a As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''pnlLegalQ03a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ03a As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDPIALegalQ03b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ03b As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cblDPIALegalQ03b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblDPIALegalQ03b As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''pnlLegalQ03b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ03b As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDPIALegalQ04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ04 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblDPIALegalQ04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDPIALegalQ04 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxDPIALegalQ04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxDPIALegalQ04 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlLegalQ04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ04 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cblDPIALegalQ04a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblDPIALegalQ04a As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''pnlLegalQ04a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegalQ04a As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDPIALegalQ04b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPIALegalQ04b As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblDPIALegalQ04b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDPIALegalQ04b As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxDPIALegalQ04b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxDPIALegalQ04b As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''vProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vProcess As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''pnlProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProcess As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''vRights control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vRights As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''pnlRights control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRights As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''vSecurity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vSecurity As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''pnlSecurity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSecurity As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''vRisks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vRisks As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''pnlRisks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRisks As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''vDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vDocuments As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''pblDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pblDocuments As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''vFinalise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vFinalise As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''pnlFinalise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFinalise As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lbtUpdateDPIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtUpdateDPIA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtSaveDPIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSaveDPIA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCloseModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseModal As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblModalHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblModalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbtAddedReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddedReturn As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtAddDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddDetail As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ModalOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalOK As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
