'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class flows_list
    
    '''<summary>
    '''dsFlows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFlows As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsOrgsSharing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsOrgsSharing As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''pnlFreeLicenceMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFreeLicenceMessage As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label16 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHideArchived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHideArchived As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbIncludeArchived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbIncludeArchived As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlShareOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShareOrg As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSharedWith control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSharedWith As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddSharingOrgs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddSharingOrgs As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bsgvExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvExporter As Global.DevExpress.Web.ASPxGridViewExporter
    
    '''<summary>
    '''bsgvFlows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvFlows As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''bsbtnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsbtnAdd As Global.DevExpress.Web.Bootstrap.BootstrapButton
End Class
