'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class home_intray
    
    '''<summary>
    '''lblUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlOrgSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOrgSetup As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''orgprog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents orgprog As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblOrgPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrgPercent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlActionList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActionList As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''firstIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firstIcon As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''eighthIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eighthIcon As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtAddContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddContact As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''secondIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents secondIcon As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtRegAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtRegAdmin As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''thirdIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thirdIcon As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtRegSenior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtRegSenior As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtRegSeniorVideo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtRegSeniorVideo As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''liDPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDPO As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ninthIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ninthIcon As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtRegDPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtRegDPO As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''fourthIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fourthIcon As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtAssurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAssurance As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtAssuranceVideo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAssuranceVideo As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''fifthIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fifthIcon As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtMOU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtMOU As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtMOUVideo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtMOUVideo As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''dsNotices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsNotices As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''pnlNotices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNotices As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblNotificationCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotificationCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptNotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptNotifications As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''cbSubSANotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSubSANotifications As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblForAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForAttention As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TOUAcknowledge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TOUAcknowledge As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litTOUSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTOUSummary As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LinkButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtAgreeTOU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAgreeTOU As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ICOExpired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ICOExpired As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pnlIcoExpiry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIcoExpiry As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlIcoExpiryHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIcoExpiryHead As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblICOExpiryHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblICOExpiryHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlExpiryBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlExpiryBody As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblICOExpiryBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblICOExpiryBody As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbtOrgAssurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtOrgAssurance As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''dsNewAssurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsNewAssurance As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''divNewSubmissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewSubmissions As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvNewAssuranceSubs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvNewAssuranceSubs As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''cbNewAssuranceNotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNewAssuranceNotifications As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlSignatureRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSignatureRequests As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''dsSignOffRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsSignOffRequests As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''gvSignOffRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSignOffRequests As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''cbDataFlowSignOffRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDataFlowSignOffRequests As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlDPOReviewRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDPOReviewRequests As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''dsDPOReviewRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDPOReviewRequests As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''gvDPOReviewRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDPOReviewRequests As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''cbDPOReviewRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDPOReviewRequests As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlDPOReviewsCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDPOReviewsCompleted As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''dsDPOReviewsCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDPOReviewsCompleted As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''gvDPOReviewsCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDPOReviewsCompleted As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblReviewsCompleteNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewsCompleteNotice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlAckReviewSignOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAckReviewSignOff As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''dsAckReviewSignOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAckReviewSignOff As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''gvAckReviewSignOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAckReviewSignOff As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''videosrc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents videosrc As Global.System.Web.UI.HtmlControls.HtmlSource
    
    '''<summary>
    '''vidparm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vidparm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
