'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class home_reports
    
    '''<summary>
    '''mvReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvReports As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''vReportMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vReportMenu As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''lbtSharingPartnersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSharingPartnersList As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtDataAssetsReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDataAssetsReport As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtDataFlows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDataFlows As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''vNoAdminGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vNoAdminGroup As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''lbtContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtContact As Global.System.Web.UI.WebControls.LinkButton
End Class
