'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class org_assurance
    
    '''<summary>
    '''dsCyberEssentials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCyberEssentials As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''mvAssurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvAssurance As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''vCurrentAssurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vCurrentAssurance As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''dsCurrentAssurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCurrentAssurance As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''fvCurrentAssurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvCurrentAssurance As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''lbtAddAssurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddAssurance As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''dsTierZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTierZero As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''Li1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fvUsageAgreement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvUsageAgreement As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''lbtViewAgreement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtViewAgreement As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlWhoCanSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWhoCanSign As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lbtSignAgreement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSignAgreement As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''vSubmitAssurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vSubmitAssurance As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''upnlICOReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlICOReg As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblICOReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblICOReg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblICOReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblICOReg As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rfvICOReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvICOReg As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''divICODetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divICODetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblICORegNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblICORegNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbICORegNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbICORegNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvICORegNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvICORegNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblICORegReviewDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblICORegReviewDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbICOReviewDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbICOReviewDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvICOReviewDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvICOReviewDate As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''revICOReviewDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revICOReviewDate As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''divICONotRegReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divICONotRegReason As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblICONotRegReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblICONotRegReason As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbICONotRegReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbICONotRegReason As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvICONotRegReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvICONotRegReason As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''dsComplianceTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsComplianceTypes As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''upnlCompliance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlCompliance As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblComplianceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComplianceType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddCompliance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddCompliance As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rfvCompliance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCompliance As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''divComplianceScoreVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divComplianceScoreVersion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScore As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbScore As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblToolkitVerion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToolkitVerion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbToolkitVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbToolkitVersion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divNonComplianceReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNonComplianceReason As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblNonComplianceReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNonComplianceReason As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbNonComplianceReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNonComplianceReason As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''upnlStaffScreened control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlStaffScreened As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblScreened control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreened As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreened control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreened As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rfvScreened control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvScreened As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''divStaffScreeningDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStaffScreeningDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblStaffScreeningDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStaffScreeningDetails As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbStaffScreeningDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbStaffScreeningDetails As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divNoScreeningReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNoScreeningReason As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblNoScreeningReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoScreeningReason As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbNoScreeningReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNoScreeningReason As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''upnlStaffTrained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlStaffTrained As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblTrained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTrained As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblIGTrained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblIGTrained As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rfvTrained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTrained As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''divStaffTrained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStaffTrained As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblIGTrainingType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIGTrainingType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbIGTrainingType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbIGTrainingType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divStaffNotTrained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStaffNotTrained As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblNoIGTrainingReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoIGTrainingReason As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbNoIGTrainingReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNoIGTrainingReason As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCyberEssentials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCyberEssentials As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddCyberEssentials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddCyberEssentials As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblPrivacyNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrivacyNotice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbPN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbtSubmitAssurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSubmitAssurance As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtCancelInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtCancelInsert As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''vSignAgreement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vSignAgreement As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''litMOUTextSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMOUTextSO As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''divDecision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDecision As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblAgreeOrganisation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAgreeOrganisation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAgreeOrganisation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAgreeOrganisation2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAgreeUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAgreeUserName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAgreeRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAgreeRole As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOnBehalfOf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnBehalfOf As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dsAgreementFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAgreementFiles As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''rptFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptFiles As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFileUpload As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''filEvidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filEvidence As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbtUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtUpload As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtFinalSignAgreement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtFinalSignAgreement As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtCancelSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtCancelSign As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''litMOUView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMOUView As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblModalHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblModalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalText As Global.System.Web.UI.WebControls.Label
End Class
