'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class org_details
    
    '''<summary>
    '''dsOrgTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsOrgTypes As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsOrganisation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsOrganisation As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsLeadOrgs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsLeadOrgs As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''fvCentreDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvCentreDetails As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''hfUploadType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfUploadType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblModalHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''filEvidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filEvidence As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lblModalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbtUploadEvidenceOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtUploadEvidenceOK As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''modalTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''modalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''modalRequestCloseTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalRequestCloseTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''modalRequestCloseLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalRequestCloseLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSeniorUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeniorUsers As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReason As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReason As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbtRequestCloseConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtRequestCloseConfirm As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtRequestCloseCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtRequestCloseCancel As Global.System.Web.UI.WebControls.LinkButton
End Class
