'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class screening_questions
    
    '''<summary>
    '''hfProjectFileGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfProjectFileGroup As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfProjectID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfProjectID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfReadOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfReadOnly As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfScreeningValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfScreeningValidation As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfPFrozen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPFrozen As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfScreeningStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfScreeningStatus As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnlSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSummary As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblFormTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblScreeningQ01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ01 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ01 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator01 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ02 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ02 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator02 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ03 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ03 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator03 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlSchedOne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSchedOne As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblScreeningQ04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ04 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ04 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator04 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ05 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ05 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator05 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ06 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ06 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ06 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ06 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator06 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator06 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ07 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ07 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator07 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ08 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ08 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator08 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ09 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ09 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ09 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ09 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator09 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator09 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ10 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ10 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator10 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ11 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ11 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator11 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ12 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ12 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator12 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ13 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ13 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator13 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ14 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ14 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator14 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ15 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ15 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator15 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ16 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ16 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator16 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ17 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ17 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator17 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningQ18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningQ18 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningQ18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningQ18 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RequiredFieldValidator18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator18 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlSchedTwo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSchedTwo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DPIARequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DPIARequired As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlSchedThree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSchedThree As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''IGLeadRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IGLeadRequired As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddIGLead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddIGLead As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RequiredIGLead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredIGLead As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''dsIGLeads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsIGLeads As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''pnlSchedFour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSchedFour As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DPIANotRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DPIANotRequired As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbtUpdateSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtUpdateSummary As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtSaveProjectScreening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSaveProjectScreening As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCloseModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseModal As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblModalHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblModalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbtAddedReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddedReturn As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtAddDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddDetail As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ModalOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalOK As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
