'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class screening_questions_v2
    
    '''<summary>
    '''hfProjectFileGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfProjectFileGroup As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfProjectID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfProjectID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfReadOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfReadOnly As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfScreeningValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfScreeningValidation As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfPFrozen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPFrozen As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfScreeningStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfScreeningStatus As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnlSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSummary As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblFormTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlQ1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQ1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblScreeningV2Q01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q01 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblScreeningV2Q01a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q01a As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q01a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q01a As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q01a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q01a As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q01b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q01b As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q01b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q01b As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q01b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q01b As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q01c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q01c As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q01c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q01c As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q01c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q01c As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q01d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q01d As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q01d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q01d As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q01d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q01d As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q01e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q01e As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q01e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q01e As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q01e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q01e As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q01f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q01f As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q01f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q01f As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q01f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q01f As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlQ2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQ2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblScreeningV2Q02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q02 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblScreeningV2Q02a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q02a As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q02a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q02a As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q02a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q02a As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q02b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q02b As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q02b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q02b As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q02b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q02b As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q02c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q02c As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q02c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q02c As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q02c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q02c As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q02d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q02d As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q02d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q02d As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q02d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q02d As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q02e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q02e As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q02e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q02e As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q02e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q02e As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q02f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q02f As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q02f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q02f As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q02f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q02f As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlQ3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQ3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblScreeningV2Q03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q03 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblScreeningV2Q03a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q03a As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q03a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q03a As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q03a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q03a As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q03b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q03b As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q03b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q03b As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q03b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q03b As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q03c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q03c As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q03c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q03c As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q03c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q03c As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q03d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q03d As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q03d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q03d As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q03d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q03d As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q03e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q03e As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q03e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q03e As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q03e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q03e As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q03f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q03f As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q03f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q03f As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q03f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q03f As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q03g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q03g As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q03g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q03g As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q03g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q03g As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q03h control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q03h As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q03h control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q03h As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q03h control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q03h As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlQ4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQ4 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblScreeningV2Q04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q04 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblScreeningV2Q04a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q04a As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q04a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q04a As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q04a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q04a As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q04b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q04b As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q04b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q04b As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q04b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q04b As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q04c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q04c As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q04c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q04c As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q04c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q04c As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q04d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q04d As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q04d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q04d As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q04d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q04d As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q04e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q04e As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q04e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q04e As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q04e control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q04e As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q04f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q04f As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q04f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q04f As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q04f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q04f As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q04g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q04g As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q04g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q04g As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q04g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q04g As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblScreeningV2Q04h control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScreeningV2Q04h As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblScreeningV2Q04h control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblScreeningV2Q04h As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rvxScreeningV2Q04h control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvxScreeningV2Q04h As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlDPIARequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDPIARequired As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DPIARequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DPIARequired As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlIGleadReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIGleadReview As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''IGLeadRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IGLeadRequired As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddIGLead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddIGLead As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RequiredIGLead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredIGLead As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lds_GetOrgIGRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lds_GetOrgIGRoles As Global.System.Web.UI.WebControls.LinqDataSource
    
    '''<summary>
    '''pnlDPIANotRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDPIANotRequired As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DPIANotRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DPIANotRequired As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbtUpdateSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtUpdateSummary As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtSaveProjectScreening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSaveProjectScreening As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCloseModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseModal As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblModalHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblModalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbtAddedReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddedReturn As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtAddDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddDetail As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ModalOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalOK As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
