'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class support_tickets
    
    '''<summary>
    '''mvSupportTickets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvSupportTickets As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''vTicketList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vTicketList As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''dsTickets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTickets As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsAdminGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAdminGroups As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''FilterPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilterPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblShowClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShowClosed As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbShowClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShowClosed As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblAddedByOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedByOrg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbAddedByMyOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAddedByMyOrg As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlSAMine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSAMine As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbShowAssigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShowAssigned As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlAdminGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdminGroup As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblAdminGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdminGroup As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddAdminGroupFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddAdminGroupFilter As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbtUpdateFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtUpdateFilter As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''gvTickets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTickets As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lbtRaiseTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtRaiseTicket As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''vAddTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAddTicket As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''lblSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubject As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSubject As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''htmlNewTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents htmlNewTicket As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditor
    
    '''<summary>
    '''lbtCancelNewTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtCancelNewTicket As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtSubmitNewSupportTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSubmitNewSupportTicket As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''vManageTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vManageTicket As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''dsTicketComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTicketComments As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''hfTicketID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTicketID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfReporterEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfReporterEmail As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblTicketHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicketHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbtArchiveTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtArchiveTicket As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtEscalate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtEscalate As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlAssignTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAssignTo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnAssignTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAssignTo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblAssignTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAssignTo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dsReassigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsReassigns As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''rptAssignTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAssignTo As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lbtRemoveAssign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtRemoveAssign As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPriority As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblResolveByDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResolveByDD As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbtSameDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSameDay As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtNextDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtNextDay As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtOneWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtOneWeek As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtChangeRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtChangeRequest As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtCloseTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtCloseTicket As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblTicketSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicketSubject As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTicketStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicketStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAddedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAddedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblResolveBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResolveBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''NewCommentPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewCommentPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''htmlAddComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents htmlAddComment As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditor
    
    '''<summary>
    '''lbtSubmitNewComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSubmitNewComment As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''rptComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptComments As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''vNoTickets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vNoTickets As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''lbtContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtContact As Global.System.Web.UI.WebControls.LinkButton
End Class
